package com.cavss.artravel.types

enum class ThemeType(val rawValue : String){
    HEALING("HEALING"),
    HISTORY("HISTORY"),
    FOODIE("FOODIE"),
    CAMPING("CAMPING"),
    ACTIVITY("ACTIVITY"),
    SURFING("SURFING"),
    MOUNTAIN("MOUNTAIN"),
    TRAIN("TRAIN"),
    LIBERAL_ARTS("LIBERAL_ARTS"),
    TEMPLE_BUDDISM("TEMPLE_BUDDISM"),
    TEMPLE_CATHOLIC("TEMPLE_CATHOLIC"),
    SPRING_FESTIVAL("SPRING_FESTIVAL"),
    SUMMER_FESTIVAL("SUMMER_FESTIVAL"),
    AUTUMN_FESTIVAL("AUTUMN_FESTIVAL"),
    WINTER_FESTIVAL("WINTER_FESTIVAL"),
    LOCAL_TRIP("LOCAL_TRIP"),
    SPA("SPA")
}
